In [1]:
import pandas as pd

In [12]:
data = pd.read_csv("../playground-series-s3e8/train.csv")
data.head(10)

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453
5   5   1.51  Very Good     J     SI1   62.8   58.0  7.34  7.29  4.59   7506
6   6   0.74      Ideal     E     VS2   61.8   57.0  5.76  5.79  3.57   3229
7   7   1.34    Premium     G     SI2   62.5   57.0  7.00  7.05  4.38   6224
8   8   0.30      Ideal     F      IF   62.0   56.0  4.35  4.37  2.70    886
9   9   0.30       Good     J     VS1   63.6   57.0  4.26  4.28  2.72    421

In [11]:
data["color"].value_counts()

color
G    44391
E    35869
F    34258
H    30799
D    24286
I    17514
J     6456
Name: count, dtype: int64

data.sample(10)

In [13]:
data.sample(10)

,id,carat,cut,color,clarity,depth,table,x,y,z,price
86596,86596,0.37,Ideal,D,SI1,62.5,55.0,4.61,4.62,2.88,818
186887,186887,1.14,Ideal,F,VS2,60.0,57.0,6.78,6.83,4.08,8074
65661,65661,2.54,Ideal,I,SI1,62.9,56.0,8.68,8.65,5.46,17784
3829,3829,1.00,Very Good,J,SI2,63.3,59.0,6.34,6.25,3.99,3461
161807,161807,0.53,Ideal,E,VS2,61.4,56.0,5.22,5.19,3.20,1711
73495,73495,0.30,Good,G,VVS2,63.8,57.0,4.22,4.26,2.70,684
109581,109581,1.00,Ideal,G,SI1,61.9,54.0,6.43,6.48,3.99,4862
114693,114693,0.41,Very Good,G,VVS1,60.7,57.0,4.82,4.85,2.93,1096
104237,104237,0.51,Ideal,H,VS1,61.7,57.0,5.11,5.14,3.16,1436
182942,182942,0.81,Ideal,G,VS2,62.5,57.0,5.91,5.94,3.70,3344

In [15]:
data.isnull().sum()

id         0
carat      0
cut        0
color      0
clarity    0
depth      0
table      0
x          0
y          0
z          0
price      0
dtype: int64

In [17]:
data.shape

(193573, 11)

In [21]:
data.drop(labels=["id"], axis=1)

KeyError: "['id'] not found in axis"

In [23]:
print (data.head(5))

   carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [32]:
cat_columns = data.columns[data.dtypes=="object"]
data[cat_columns]

              cut color clarity
0         Premium     F     VS2
1       Very Good     J     SI2
2           Ideal     G     VS1
3           Ideal     G     VS1
4         Premium     G     VS2
...           ...   ...     ...
193568      Ideal     D    VVS2
193569    Premium     G    VVS2
193570  Very Good     F     SI1
193571  Very Good     D     SI1
193572       Good     E     SI2

[193573 rows x 3 columns]

In [30]:
data[cat_columns]

NameError: name 'cat_columns' is not defined